### ISSUE TITLE
Non-deterministic behavior in System execution

### ISSUE THREAD

**Issue by rphmeier** [rphmeier/rust_toy_engine#9]
Currently, systems are executed in a pipeline model. ComponentMappers are passed mutably to each system, along with a list of entities which hold the requisite components, and then the updated ComponentMappers are used to find the entities for the next system, which can in turn alter the state of the world. Since systems can execute in arbitrary order, this poses a serious problem.

After some thought, I've arrived at a solution which seems to address this issue:
- Freeze the world state before executing systems, so that all systems see the same state. 
- Collect changes from every system to be applied after all systems are run. 
- Changes will be grouped into two categories: commutative and non-commutative. Infinitely many commutative changes may be made to a single component, but it will be an error to make more than one non-commutative change to a component if any of those changes are found to be conflicting. 

This can be streamlined by an API which takes the burden of deferring changes mostly off of the user. This needs to be designed.

**Comment by rphmeier** [comment]
Renamed because this is not technically a race condition, as it is not caused by multiple threads accessing the same date.

**Comment by vjrao** [comment]
Rather than entirely preventing non-commutative changes from occurring in the same update, perhaps some changes could be summarized by an order of precedence and then applied simultaneously. For example, a position set change would have priority over a translation, but two position set changes would have equal priority and so only the one first submitted to the system would be applied.

**Comment by rphmeier** [comment]
Unfortunately, that is not sufficient. The game code should behave the exact same way given the exact same inputs. If the systems are executed concurrently, it is impossible to know which conflicting non-commutative change will be submitted first. If multiple systems submit a non-commutative change to the same component of the same entity, that should be considered an invalid state and should be handled like one. The exception is if it can be proven that the non-commutative changes do not interfere with each other. Additionally, any non-commutative changes should be applied before commutative changes.

**Comment by vjrao** [comment]
Is it necessary to handle the situation of multiple non-commutative changes as an error? Given arbitrary user input, it seems much harder to structure the game to prevent more than one change from being simultaneously submitted than to simply handle the case with, for example, an order of precedence for changes. I understand that it would bring about some extra and usually unnecessary processing time for changes, but to just crash on certain occasions seems like asking for trouble.

**Comment by rphmeier** [comment]
There could be multiple behaviors that can be chosen when this situation occurs:
- Exit with error message
- Ignore the incompatible non-commutative change and log an error message
- Ignore and do not log

However,  I do not recommend choosing to fail silently. While these occurrences will likely be very  rare, they indicate that the developer is writing code which depends on systems to run in a specific order. System processing is documented to run in an arbitrary order, and the actual order systems are run in is an implementation detail which can change at any time. At the very least,  running into this edge case at all is a symptom of a serious design error in a program that uses the engine, and the failing silently is not a good way to make that apparent to the developer.

**Comment by rphmeier** [comment]
Closing because of new design
